[2025-01-28T11:39:43.731+0530] {processor.py:186} INFO - Started process (PID=17141) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:39:43.732+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:39:43.735+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:39:43.734+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:39:43.737+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:39:43.737+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:39:43.738+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:39:43.738+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:39:43.738+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:39:43.746+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-01-28T11:40:42.910+0530] {processor.py:186} INFO - Started process (PID=17333) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:40:42.922+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:40:42.925+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:40:42.924+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:40:42.927+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:40:42.927+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:40:42.928+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:40:42.928+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:40:42.928+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:40:42.935+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T11:41:37.459+0530] {processor.py:186} INFO - Started process (PID=17495) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:41:37.471+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:41:37.474+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:41:37.473+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:41:37.476+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:41:37.476+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:41:37.477+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:41:37.476+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:41:37.477+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:41:37.484+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T11:42:34.128+0530] {processor.py:186} INFO - Started process (PID=17690) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:42:34.141+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:42:34.143+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:42:34.142+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:42:34.145+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:42:34.145+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:42:34.146+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:42:34.146+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:42:34.146+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:42:34.153+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T11:43:25.557+0530] {processor.py:186} INFO - Started process (PID=17849) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:43:25.558+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:43:25.560+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:43:25.559+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:43:25.562+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:43:25.562+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:43:25.562+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:43:25.562+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:43:25.563+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:43:25.570+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-01-28T11:44:14.731+0530] {processor.py:186} INFO - Started process (PID=18006) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:44:14.744+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:44:14.746+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:44:14.746+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:44:14.748+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:44:14.748+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:44:14.749+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:44:14.749+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:44:14.749+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:44:14.756+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T11:45:05.651+0530] {processor.py:186} INFO - Started process (PID=18184) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:45:05.663+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:45:05.664+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:45:05.664+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:45:05.667+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:45:05.666+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:45:05.667+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:45:05.667+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:45:05.667+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:45:05.679+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-01-28T11:46:01.477+0530] {processor.py:186} INFO - Started process (PID=18361) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:46:01.489+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:46:01.496+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:46:01.496+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:46:01.499+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:46:01.499+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:46:01.500+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:46:01.499+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:46:01.500+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:46:01.509+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-01-28T11:46:54.137+0530] {processor.py:186} INFO - Started process (PID=18569) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:46:54.138+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:46:54.141+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:46:54.140+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:46:54.143+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:46:54.143+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:46:54.143+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:46:54.143+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:46:54.144+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:46:54.151+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-01-28T11:47:45.530+0530] {processor.py:186} INFO - Started process (PID=18916) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:47:45.542+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:47:45.544+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:47:45.544+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:47:45.547+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:47:45.546+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:47:45.547+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:47:45.547+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:47:45.547+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:47:45.555+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T11:48:39.318+0530] {processor.py:186} INFO - Started process (PID=19133) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:48:39.331+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:48:39.333+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:48:39.333+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:48:39.336+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:48:39.335+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:48:39.336+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:48:39.336+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:48:39.336+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:48:39.344+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-01-28T11:49:30.818+0530] {processor.py:186} INFO - Started process (PID=19449) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:49:30.830+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:49:30.832+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:49:30.832+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:49:30.835+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:49:30.834+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:49:30.835+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:49:30.835+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:49:30.835+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:49:30.843+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T11:50:17.903+0530] {processor.py:186} INFO - Started process (PID=19767) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:50:17.915+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:50:17.918+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:50:17.917+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:50:17.920+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:50:17.920+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:50:17.920+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:50:17.920+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:50:17.921+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:50:17.928+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T11:51:09.837+0530] {processor.py:186} INFO - Started process (PID=19891) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:51:09.838+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:51:09.840+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:51:09.840+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:51:09.843+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:51:09.842+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:51:09.843+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:51:09.843+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:51:09.843+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:51:09.852+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-01-28T11:52:00.762+0530] {processor.py:186} INFO - Started process (PID=20322) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:52:00.774+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:52:00.777+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:52:00.776+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:52:00.780+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:52:00.779+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:52:00.780+0530] {logging_mixin.py:190} INFO - [2025-01-28T11:52:00.780+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:52:00.780+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:52:00.788+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:01:17.115+0530] {processor.py:186} INFO - Started process (PID=22914) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:01:17.127+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:01:17.130+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:01:17.130+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:01:17.133+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:01:17.133+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:01:17.133+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:01:17.133+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:01:17.134+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:01:17.143+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-01-28T12:02:13.728+0530] {processor.py:186} INFO - Started process (PID=23302) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:02:13.740+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:02:13.742+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:02:13.742+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:02:13.745+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:02:13.744+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:02:13.745+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:02:13.745+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:02:13.746+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:02:13.754+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-01-28T12:03:58.047+0530] {processor.py:186} INFO - Started process (PID=24494) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:03:58.060+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:03:58.062+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:03:58.062+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:03:58.065+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:03:58.064+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:03:58.065+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:03:58.065+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:03:58.065+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:03:58.073+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:04:51.830+0530] {processor.py:186} INFO - Started process (PID=24960) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:04:51.831+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:04:51.833+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:04:51.833+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:04:51.837+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:04:51.836+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:04:51.837+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:04:51.837+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:04:51.837+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:04:51.847+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T12:05:43.988+0530] {processor.py:186} INFO - Started process (PID=25234) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:05:44.001+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:05:44.004+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:05:44.003+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:05:44.007+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:05:44.006+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:05:44.007+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:05:44.007+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:05:44.008+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:05:44.017+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-01-28T12:06:33.957+0530] {processor.py:186} INFO - Started process (PID=25509) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:06:33.970+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:06:33.972+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:06:33.972+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:06:33.975+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:06:33.974+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:06:33.975+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:06:33.975+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:06:33.975+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:06:33.983+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-01-28T12:07:22.066+0530] {processor.py:186} INFO - Started process (PID=25751) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:07:22.078+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:07:22.080+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:07:22.080+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:07:22.083+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:07:22.083+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:07:22.083+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:07:22.083+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:07:22.083+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:07:22.091+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:08:13.800+0530] {processor.py:186} INFO - Started process (PID=26076) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:08:13.812+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:08:13.814+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:08:13.814+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:08:13.817+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:08:13.816+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:08:13.817+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:08:13.817+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:08:13.817+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:08:13.825+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-01-28T12:09:05.623+0530] {processor.py:186} INFO - Started process (PID=26508) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:09:05.635+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:09:05.638+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:09:05.638+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:09:05.640+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:09:05.640+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:09:05.641+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:09:05.641+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:09:05.641+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:09:05.648+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:09:55.334+0530] {processor.py:186} INFO - Started process (PID=26912) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:09:55.335+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:09:55.337+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:09:55.337+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:09:55.340+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:09:55.340+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:09:55.340+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:09:55.340+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:09:55.340+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:09:55.348+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-01-28T12:10:45.604+0530] {processor.py:186} INFO - Started process (PID=27186) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:10:45.605+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:10:45.607+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:10:45.607+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:10:45.610+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:10:45.609+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:10:45.610+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:10:45.610+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:10:45.610+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:10:45.618+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-01-28T12:11:37.128+0530] {processor.py:186} INFO - Started process (PID=27539) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:11:37.140+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:11:37.142+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:11:37.141+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:11:37.144+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:11:37.144+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:11:37.144+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:11:37.144+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:11:37.144+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:11:37.152+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:12:28.385+0530] {processor.py:186} INFO - Started process (PID=27968) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:12:28.386+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:12:28.388+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:12:28.388+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:12:28.392+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:12:28.391+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:12:28.392+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:12:28.392+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:12:28.392+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:12:28.400+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-01-28T12:13:20.937+0530] {processor.py:186} INFO - Started process (PID=28352) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:13:20.949+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:13:20.952+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:13:20.952+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:13:20.955+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:13:20.954+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:13:20.955+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:13:20.955+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:13:20.955+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:13:20.963+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:14:10.042+0530] {processor.py:186} INFO - Started process (PID=28791) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:14:10.043+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:14:10.045+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:14:10.045+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:14:10.048+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:14:10.047+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:14:10.048+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:14:10.048+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:14:10.048+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:14:10.056+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-01-28T12:15:00.290+0530] {processor.py:186} INFO - Started process (PID=29463) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:15:00.302+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:15:00.305+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:15:00.304+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:15:00.307+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:15:00.307+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:15:00.307+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:15:00.307+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:15:00.308+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:15:00.315+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-01-28T12:15:52.800+0530] {processor.py:186} INFO - Started process (PID=30063) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:15:52.812+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:15:52.814+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:15:52.814+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:15:52.816+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:15:52.816+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:15:52.816+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:15:52.816+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:15:52.817+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:15:52.824+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-01-28T12:16:44.217+0530] {processor.py:186} INFO - Started process (PID=30223) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:16:44.230+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:16:44.232+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:16:44.232+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:16:44.235+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:16:44.234+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:16:44.235+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:16:44.235+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:16:44.235+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:16:44.243+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:17:35.613+0530] {processor.py:186} INFO - Started process (PID=30444) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:17:35.614+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:17:35.616+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:17:35.615+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:17:35.619+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:17:35.618+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:17:35.619+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:17:35.619+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:17:35.619+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:17:35.627+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-01-28T12:18:26.434+0530] {processor.py:186} INFO - Started process (PID=30603) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:18:26.446+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:18:26.449+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:18:26.449+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:18:26.451+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:18:26.451+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:18:26.452+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:18:26.452+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:18:26.452+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:18:26.459+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:19:16.711+0530] {processor.py:186} INFO - Started process (PID=30760) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:19:16.724+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:19:16.727+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:19:16.727+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:19:16.729+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:19:16.729+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:19:16.730+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:19:16.730+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:19:16.730+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:19:16.737+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-01-28T12:20:09.066+0530] {processor.py:186} INFO - Started process (PID=30957) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:20:09.078+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:20:09.080+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:20:09.080+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:20:09.083+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:20:09.082+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:20:09.083+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:20:09.083+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:20:09.083+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:20:09.091+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:21:00.647+0530] {processor.py:186} INFO - Started process (PID=31172) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:21:00.660+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:21:00.662+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:21:00.661+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:21:00.664+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:21:00.664+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:21:00.664+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:21:00.664+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:21:00.664+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:21:00.672+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:21:49.791+0530] {processor.py:186} INFO - Started process (PID=31275) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:21:49.804+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:21:49.806+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:21:49.806+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:21:49.809+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:21:49.808+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:21:49.809+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:21:49.809+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:21:49.809+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:21:49.816+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:22:40.025+0530] {processor.py:186} INFO - Started process (PID=31442) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:22:40.037+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:22:40.039+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:22:40.038+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:22:40.042+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:22:40.041+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:22:40.042+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:22:40.042+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:22:40.042+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:22:40.049+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-01-28T12:23:26.299+0530] {processor.py:186} INFO - Started process (PID=31596) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:23:26.311+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:23:26.314+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:23:26.314+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:23:26.316+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:23:26.316+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:23:26.316+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:23:26.316+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:23:26.317+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:23:26.324+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:24:16.230+0530] {processor.py:186} INFO - Started process (PID=31809) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:24:16.231+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:24:16.234+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:24:16.233+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:24:16.236+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:24:16.236+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:24:16.236+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:24:16.236+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:24:16.236+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:24:16.244+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-01-28T12:25:06.916+0530] {processor.py:186} INFO - Started process (PID=32105) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:25:06.917+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:25:06.919+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:25:06.919+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:25:06.922+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:25:06.922+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:25:06.922+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:25:06.922+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:25:06.923+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:25:06.931+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-01-28T12:25:59.610+0530] {processor.py:186} INFO - Started process (PID=32422) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:25:59.623+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:25:59.626+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:25:59.625+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:25:59.628+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:25:59.628+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:25:59.629+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:25:59.629+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:25:59.629+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:25:59.637+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-01-28T12:26:51.151+0530] {processor.py:186} INFO - Started process (PID=32525) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:26:51.164+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:26:51.167+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:26:51.167+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:26:51.170+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:26:51.170+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:26:51.170+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:26:51.170+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:26:51.170+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:26:51.180+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-01-28T12:27:43.843+0530] {processor.py:186} INFO - Started process (PID=32695) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:27:43.856+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:27:43.859+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:27:43.858+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:27:43.862+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:27:43.861+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:27:43.862+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:27:43.862+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:27:43.862+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:27:43.871+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-01-28T12:28:39.051+0530] {processor.py:186} INFO - Started process (PID=32861) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:28:39.065+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:28:39.070+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:28:39.069+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:28:39.072+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:28:39.072+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:28:39.073+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:28:39.072+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:28:39.073+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:28:39.082+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-01-28T12:29:28.105+0530] {processor.py:186} INFO - Started process (PID=33051) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:29:28.117+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:29:28.119+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:29:28.119+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:29:28.122+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:29:28.122+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:29:28.122+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:29:28.122+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:29:28.122+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:29:28.136+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-01-28T12:30:21.661+0530] {processor.py:186} INFO - Started process (PID=33234) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:30:21.673+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:30:21.676+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:30:21.675+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:30:21.679+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:30:21.678+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:30:21.679+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:30:21.679+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:30:21.679+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:30:21.692+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-01-28T12:31:12.891+0530] {processor.py:186} INFO - Started process (PID=33451) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:31:12.903+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:31:12.906+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:31:12.905+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:31:12.908+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:31:12.908+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:31:12.908+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:31:12.908+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:31:12.909+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:31:12.918+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-01-28T12:32:03.054+0530] {processor.py:186} INFO - Started process (PID=33617) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:32:03.067+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:32:03.070+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:32:03.069+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:32:03.072+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:32:03.072+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:32:03.073+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:32:03.073+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:32:03.073+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:32:03.087+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-01-28T12:32:58.241+0530] {processor.py:186} INFO - Started process (PID=33810) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:32:58.243+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:32:58.245+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:32:58.244+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:32:58.248+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:32:58.247+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:32:58.248+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:32:58.248+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:32:58.248+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:32:58.260+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-01-28T12:33:51.225+0530] {processor.py:186} INFO - Started process (PID=33960) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:33:51.230+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:33:51.244+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:33:51.243+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:33:51.261+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:33:51.258+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:33:51.262+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:33:51.262+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:33:51.263+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:33:51.302+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.101 seconds
[2025-01-28T12:34:50.034+0530] {processor.py:186} INFO - Started process (PID=34172) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:34:50.046+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:34:50.049+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:34:50.049+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:34:50.052+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:34:50.051+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:34:50.052+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:34:50.052+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:34:50.052+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:34:50.062+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-01-28T12:35:41.345+0530] {processor.py:186} INFO - Started process (PID=34337) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:35:41.357+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:35:41.360+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:35:41.360+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:35:41.363+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:35:41.362+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:35:41.363+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:35:41.363+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:35:41.363+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:35:41.374+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-01-28T12:36:32.769+0530] {processor.py:186} INFO - Started process (PID=34566) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:36:32.782+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:36:32.784+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:36:32.784+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:36:32.787+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:36:32.787+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:36:32.787+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:36:32.787+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:36:32.787+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:36:32.797+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-01-28T12:37:26.342+0530] {processor.py:186} INFO - Started process (PID=34734) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:37:26.355+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:37:26.357+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:37:26.357+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:37:26.360+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:37:26.359+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:37:26.360+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:37:26.360+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:37:26.360+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:37:26.371+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-01-28T12:38:16.001+0530] {processor.py:186} INFO - Started process (PID=34900) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:38:16.013+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:38:16.015+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:38:16.015+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:38:16.018+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:38:16.018+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:38:16.018+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:38:16.018+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:38:16.019+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:38:16.029+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-01-28T12:39:06.344+0530] {processor.py:186} INFO - Started process (PID=35058) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:39:06.353+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:39:06.355+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:39:06.354+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:39:06.358+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:39:06.357+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:39:06.358+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:39:06.358+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:39:06.358+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:39:06.366+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-01-28T12:39:56.305+0530] {processor.py:186} INFO - Started process (PID=35267) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:39:56.317+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:39:56.320+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:39:56.320+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:39:56.323+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:39:56.322+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:39:56.323+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:39:56.323+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:39:56.323+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:39:56.331+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:40:47.835+0530] {processor.py:186} INFO - Started process (PID=35466) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:40:47.848+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:40:47.851+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:40:47.851+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:40:47.854+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:40:47.853+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:40:47.854+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:40:47.854+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:40:47.854+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:40:47.862+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-01-28T12:41:34.342+0530] {processor.py:186} INFO - Started process (PID=35980) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:41:34.343+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:41:34.345+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:41:34.345+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:41:34.348+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:41:34.347+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:41:34.348+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:41:34.348+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:41:34.348+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:41:34.356+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-01-28T12:42:25.517+0530] {processor.py:186} INFO - Started process (PID=36357) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:42:25.532+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:42:25.535+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:42:25.535+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:42:25.538+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:42:25.537+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:42:25.538+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:42:25.538+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:42:25.538+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:42:25.546+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-01-28T12:43:19.179+0530] {processor.py:186} INFO - Started process (PID=36790) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:43:19.192+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:43:19.195+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:43:19.195+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:43:19.198+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:43:19.197+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:43:19.198+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:43:19.198+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:43:19.198+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:43:19.206+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-01-28T12:44:09.500+0530] {processor.py:186} INFO - Started process (PID=37076) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:44:09.512+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:44:09.514+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:44:09.513+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:44:09.517+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:44:09.516+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:44:09.517+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:44:09.517+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:44:09.517+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:44:09.524+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-01-28T12:44:57.514+0530] {processor.py:186} INFO - Started process (PID=37332) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:44:57.515+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:44:57.518+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:44:57.518+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:44:57.521+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:44:57.521+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:44:57.522+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:44:57.521+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:44:57.522+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:44:57.530+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-01-28T12:45:46.059+0530] {processor.py:186} INFO - Started process (PID=37640) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:45:46.071+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:45:46.073+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:45:46.073+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:45:46.076+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:45:46.075+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:45:46.076+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:45:46.076+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:45:46.076+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:45:46.084+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:46:36.298+0530] {processor.py:186} INFO - Started process (PID=37917) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:46:36.299+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:46:36.301+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:46:36.301+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:46:36.304+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:46:36.303+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:46:36.304+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:46:36.304+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:46:36.304+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:46:36.313+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-01-28T12:47:30.016+0530] {processor.py:186} INFO - Started process (PID=38130) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:47:30.030+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:47:30.033+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:47:30.033+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:47:30.037+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:47:30.036+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:47:30.037+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:47:30.037+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:47:30.037+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:47:30.045+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-01-28T12:48:22.843+0530] {processor.py:186} INFO - Started process (PID=38352) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:48:22.856+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:48:22.859+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:48:22.858+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:48:22.861+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:48:22.861+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:48:22.861+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:48:22.861+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:48:22.862+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:48:22.869+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:49:13.901+0530] {processor.py:186} INFO - Started process (PID=38639) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:49:13.914+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:49:13.917+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:49:13.916+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:49:13.920+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:49:13.919+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:49:13.920+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:49:13.920+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:49:13.920+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:49:13.929+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-01-28T12:50:06.217+0530] {processor.py:186} INFO - Started process (PID=38916) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:50:06.217+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:50:06.220+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:50:06.219+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:50:06.222+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:50:06.222+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:50:06.222+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:50:06.222+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:50:06.223+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:50:06.231+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-01-28T12:50:56.295+0530] {processor.py:186} INFO - Started process (PID=39155) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:50:56.296+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:50:56.298+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:50:56.298+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:50:56.300+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:50:56.300+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:50:56.300+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:50:56.300+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:50:56.301+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:50:56.309+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-01-28T12:51:47.452+0530] {processor.py:186} INFO - Started process (PID=39381) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:51:47.453+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:51:47.455+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:51:47.455+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:51:47.458+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:51:47.457+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:51:47.458+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:51:47.458+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:51:47.458+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:51:47.466+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-01-28T12:52:43.895+0530] {processor.py:186} INFO - Started process (PID=39622) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:52:43.896+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:52:43.898+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:52:43.898+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:52:43.901+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:52:43.901+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:52:43.901+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:52:43.901+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:52:43.901+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:52:43.909+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-01-28T12:53:37.048+0530] {processor.py:186} INFO - Started process (PID=39853) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:53:37.061+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:53:37.063+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:53:37.063+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:53:37.066+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:53:37.065+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:53:37.066+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:53:37.066+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:53:37.066+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:53:37.073+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:54:27.273+0530] {processor.py:186} INFO - Started process (PID=40097) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:54:27.285+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:54:27.287+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:54:27.287+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:54:27.290+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:54:27.290+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:54:27.291+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:54:27.291+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:54:27.291+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:54:27.298+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:55:16.992+0530] {processor.py:186} INFO - Started process (PID=40309) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:55:16.993+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:55:16.996+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:55:16.995+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:55:16.998+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:55:16.998+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:55:16.999+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:55:16.998+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:55:16.999+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:55:17.007+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-01-28T12:56:05.892+0530] {processor.py:186} INFO - Started process (PID=40571) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:56:05.904+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:56:05.906+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:56:05.906+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:56:05.909+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:56:05.908+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:56:05.909+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:56:05.909+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:56:05.909+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:56:05.917+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T12:56:57.703+0530] {processor.py:186} INFO - Started process (PID=40795) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:56:57.715+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:56:57.717+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:56:57.717+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:56:57.720+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:56:57.720+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:56:57.721+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:56:57.721+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:56:57.721+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:56:57.729+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-01-28T12:57:47.097+0530] {processor.py:186} INFO - Started process (PID=40963) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:57:47.097+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:57:47.100+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:57:47.099+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:57:47.102+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:57:47.102+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:57:47.103+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:57:47.102+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:57:47.103+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:57:47.110+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-01-28T12:58:36.276+0530] {processor.py:186} INFO - Started process (PID=41192) to work on /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:58:36.289+0530] {processor.py:914} INFO - Processing file /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T12:58:36.292+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:58:36.292+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:58:36.295+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:58:36.294+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T12:58:36.295+0530] {logging_mixin.py:190} INFO - [2025-01-28T12:58:36.295+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T12:58:36.295+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T12:58:36.304+0530] {processor.py:208} INFO - Processing /home/verma-tv/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
